### ISSUE TITLE
Port the Exercises Component from the old app

### ISSUE THREAD

**Issue by marcos8896** [brandonvilla21/nutrition-care-app#10]
Create a component that display all the current Exercises for the Administrator user.
- [ ] Add test to verify if the Create Floating button actually navigates to the CreateExercise Component. It will be required to have been implemented the CreateExercise functionality from issue [#11](https://github.com/brandonvilla21/nutrition-care-app/issues/11)
- [ ] Add button to redirect to delete functionality for the exercises - [#12](https://github.com/brandonvilla21/nutrition-care-app/issues/12).
- [ ] Add button to redirect to edit functionality for the exercises - [#13](https://github.com/brandonvilla21/nutrition-care-app/issues/13).

Related node API issue - [#30](https://github.com/marcos8896/nutrition-care-node-api/issues/30)
